/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testndkeclipse_JniClient */

#ifndef _Included_com_example_testndkeclipse_JniClient
#define _Included_com_example_testndkeclipse_JniClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testndkeclipse_JniClient
 * Method:    AddStr
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_testndkeclipse_JniClient_AddStr
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_example_testndkeclipse_JniClient
 * Method:    TestDataTypeJ2C
 * Signature: (SIJFDCZBLjava/lang/String;[ILjava/lang/Object;Lcom/example/testndkeclipse/MyJavaClass;)V
 */
JNIEXPORT void JNICALL Java_com_example_testndkeclipse_JniClient_TestDataTypeJ2C
  (JNIEnv *, jclass, jshort, jint, jlong, jfloat, jdouble, jchar, jboolean, jbyte, jstring, jintArray, jobject, jobject);

/*
 * Class:     com_example_testndkeclipse_JniClient
 * Method:    sumArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_testndkeclipse_JniClient_sumArray
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_example_testndkeclipse_JniClient
 * Method:    getArrayObjectFromC
 * Signature: (I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_testndkeclipse_JniClient_getArrayObjectFromC
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_testndkeclipse_JniClient
 * Method:    callJavaStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_testndkeclipse_JniClient_callJavaStaticMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_example_testndkeclipse_JniClient
 * Method:    callJavaInstaceMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_testndkeclipse_JniClient_callJavaInstaceMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_example_testndkeclipse_JniClient
 * Method:    accessInstanceField
 * Signature: (Lcom/example/testndkeclipse/ClassField;)V
 */
JNIEXPORT void JNICALL Java_com_example_testndkeclipse_JniClient_accessInstanceField
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_example_testndkeclipse_JniClient
 * Method:    accessStaticField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_testndkeclipse_JniClient_accessStaticField
  (JNIEnv *, jclass);

/*
 * Class:     com_example_testndkeclipse_JniClient
 * Method:    callSuperInstanceMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_testndkeclipse_JniClient_callSuperInstanceMethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
